PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, platform_role TEXT NOT NULL CHECK(platform_role IN ('OWNER','WRITER')), account_identifier TEXT NOT NULL UNIQUE, password_algorithm TEXT NOT NULL, password_iterations INTEGER NOT NULL, password_salt BLOB NOT NULL, password_digest BLOB NOT NULL, owner_initialized_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_local_draft_keys (user_id TEXT PRIMARY KEY REFERENCES users(id), wrapped_dek BLOB NOT NULL, wrap_iv BLOB NOT NULL, kek_version INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, token_hash TEXT NOT NULL UNIQUE, user_id TEXT NOT NULL REFERENCES users(id), csrf_state TEXT NOT NULL, expires_at TEXT NOT NULL, absolute_expires_at TEXT NOT NULL, revoked_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS invitations (id TEXT PRIMARY KEY, token_hash TEXT NOT NULL UNIQUE, role TEXT NOT NULL CHECK(role IN ('OWNER','WRITER','EDITOR','COMMENTER','VIEWER')), work_id TEXT, expires_at TEXT NOT NULL, max_uses INTEGER NOT NULL, use_count INTEGER NOT NULL DEFAULT 0, revoked_at TEXT, created_by TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS works (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), title TEXT NOT NULL, alternative_title TEXT, pen_name TEXT, logline TEXT, synopsis TEXT, audience TEXT, target_platform TEXT, primary_genre TEXT, secondary_genre TEXT, tags_json TEXT NOT NULL DEFAULT '[]', expected_word_count INTEGER, update_plan TEXT, status TEXT NOT NULL, copyright_note TEXT, ai_full_text_allowed INTEGER NOT NULL DEFAULT 0, kind TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 0, deleted_at TEXT, deleted_by TEXT REFERENCES users(id), delete_reason TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS work_members (work_id TEXT NOT NULL REFERENCES works(id), user_id TEXT NOT NULL REFERENCES users(id), role TEXT NOT NULL CHECK(role IN ('EDITOR','COMMENTER','VIEWER')), created_at TEXT NOT NULL, PRIMARY KEY(work_id, user_id));
CREATE TABLE IF NOT EXISTS volumes (id TEXT PRIMARY KEY, work_id TEXT NOT NULL REFERENCES works(id), title TEXT NOT NULL, position INTEGER NOT NULL, collapsed INTEGER NOT NULL DEFAULT 0, deleted_at TEXT, deleted_by TEXT REFERENCES users(id), delete_reason TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS chapters (id TEXT PRIMARY KEY, work_id TEXT NOT NULL REFERENCES works(id), volume_id TEXT NOT NULL REFERENCES volumes(id), title TEXT NOT NULL, canonical_content TEXT NOT NULL, plain_text TEXT NOT NULL, word_count INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL, position INTEGER NOT NULL, target_word_count INTEGER, plot_goal TEXT, locked INTEGER NOT NULL DEFAULT 0, hidden INTEGER NOT NULL DEFAULT 0, revision INTEGER NOT NULL DEFAULT 0, deleted_at TEXT, deleted_by TEXT REFERENCES users(id), delete_reason TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS chapter_versions (id TEXT PRIMARY KEY, chapter_id TEXT NOT NULL REFERENCES chapters(id), canonical_content TEXT NOT NULL, plain_text TEXT NOT NULL, word_count INTEGER NOT NULL, source_revision INTEGER NOT NULL, reason TEXT NOT NULL, label TEXT, created_by TEXT REFERENCES users(id), is_favorite INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS chapter_conflicts (id TEXT PRIMARY KEY, chapter_id TEXT NOT NULL REFERENCES chapters(id), current_version_id TEXT NOT NULL REFERENCES chapter_versions(id), submitted_version_id TEXT NOT NULL REFERENCES chapter_versions(id), conflict_version_id TEXT NOT NULL REFERENCES chapter_versions(id), status TEXT NOT NULL, resolved_by TEXT REFERENCES users(id), resolved_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS chapter_notes (id TEXT PRIMARY KEY, chapter_id TEXT NOT NULL REFERENCES chapters(id), author_id TEXT NOT NULL REFERENCES users(id), body TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS chapter_comments (id TEXT PRIMARY KEY, chapter_id TEXT NOT NULL REFERENCES chapters(id), author_id TEXT NOT NULL REFERENCES users(id), anchor_json TEXT, body TEXT NOT NULL, thread_status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS change_suggestions (id TEXT PRIMARY KEY, chapter_id TEXT NOT NULL REFERENCES chapters(id), author_id TEXT NOT NULL REFERENCES users(id), anchor_json TEXT NOT NULL, replacement_content TEXT NOT NULL, status TEXT NOT NULL, handled_by TEXT REFERENCES users(id), handled_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS writing_sessions (user_id TEXT NOT NULL REFERENCES users(id), date TEXT NOT NULL, added_characters INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL, PRIMARY KEY(user_id, date));
CREATE TABLE IF NOT EXISTS writing_goals (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), work_id TEXT REFERENCES works(id), week_start TEXT NOT NULL, target_characters INTEGER NOT NULL, completed_characters INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sync_operations (client_operation_id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), chapter_id TEXT NOT NULL REFERENCES chapters(id), request_digest TEXT, result_json TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS migration_runs (migration_id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), source_database TEXT NOT NULL, summary_json TEXT, status TEXT NOT NULL, error_code TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS profile_settings (user_id TEXT PRIMARY KEY REFERENCES users(id), theme TEXT NOT NULL, font_size INTEGER NOT NULL, line_height REAL NOT NULL, editor_width TEXT NOT NULL, left_column_width INTEGER NOT NULL, right_column_width INTEGER NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, actor_id TEXT REFERENCES users(id), action TEXT NOT NULL, target_type TEXT NOT NULL, target_id TEXT NOT NULL, metadata_json TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS file_metadata (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), work_id TEXT REFERENCES works(id), object_key TEXT NOT NULL UNIQUE, original_name TEXT NOT NULL, content_type TEXT NOT NULL, size_bytes INTEGER NOT NULL, content_hash TEXT NOT NULL, created_at TEXT NOT NULL);

CREATE INDEX IF NOT EXISTS works_owner_deleted_idx ON works(owner_id, deleted_at);
CREATE INDEX IF NOT EXISTS chapters_work_volume_position_idx ON chapters(work_id, volume_id, position);
CREATE INDEX IF NOT EXISTS chapter_versions_chapter_created_idx ON chapter_versions(chapter_id, created_at DESC);
CREATE INDEX IF NOT EXISTS writing_sessions_user_date_idx ON writing_sessions(user_id, date);
